BUILD_CONFIGURATION_MAKEFILE:= $(abspath $(lastword $(MAKEFILE_LIST)))
BUILD_CONFIGURATION_PATH:= $(patsubst %/,%,$(dir $(BUILD_CONFIGURATION_MAKEFILE)))
BUILD_CONFIGURATION_DIRECTORY:= $(patsubst %/,%,$(notdir $(BUILD_CONFIGURATION_PATH)))

COLOR_GREEN=\033[0;32m
COLOR_NORMAL=\033[0m

REVISION_CONTROL_HASH:=$(shell git rev-parse HEAD)

OUTPUT=$(BUILD_CONFIGURATION_PATH)/output

mkstddirs= mkdir -p $(1)/host && mkdir -p $(1)/build && mkdir -p $(1)/target && mkdir -p $(1)/images && mkdir -p $(1)/staging

EMBEDDED=$(BUILD_CONFIGURATION_PATH)/embedded
EMBEDDED_OUTPUT=$(OUTPUT)/embedded
EMBEDDED_HOST=$(EMBEDDED_OUTPUT)/host
EMBEDDED_BUILD=$(EMBEDDED_OUTPUT)/build
EMBEDDED_TARGET=$(EMBEDDED_OUTPUT)/target
EMBEDDED_IMAGES=$(EMBEDDED_OUTPUT)/images
EMBEDDED_STAGING=$(EMBEDDED_OUTPUT)/staging

HTML=$(BUILD_CONFIGURATION_PATH)/html
HTML_OUTPUT=$(OUTPUT)/html
HTML_HOST=$(HTML_OUTPUT)/host
HTML_BUILD=$(HTML_OUTPUT)/build
HTML_TARGET=$(HTML_OUTPUT)/target
HTML_IMAGES=$(HTML_OUTPUT)/images
HTML_STAGING=$(HTML_OUTPUT)/staging

JS=$(BUILD_CONFIGURATION_PATH)/js
JS_OUTPUT=$(OUTPUT)/js
JS_HOST=$(JS_OUTPUT)/host
JS_BUILD=$(JS_OUTPUT)/build
JS_TARGET=$(JS_OUTPUT)/target
JS_IMAGES=$(JS_OUTPUT)/images
JS_STAGING=$(JS_OUTPUT)/staging
